name: macOS Chrome VNC

on: [workflow_dispatch]

jobs:
  chrome-vnc:
    runs-on: macos-latest

    steps:
      - name: Prevent sleep
        run: caffeinate -dims &

      - name: Enable Screen Sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -privs -all -restart -agent -console

      - name: Hide Dock and Menu Bar
        run: |
          defaults write com.apple.dock autohide -bool true
          defaults write NSGlobalDomain _HIHideMenuBar -bool true
          killall Dock || true

      - name: Install Google Chrome
        run: |
          brew install --cask google-chrome

      - name: Install and start ngrok
        run: |
          brew install --no-quarantine ngrok
          mkdir -p ~/.ngrok2
          echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ~/.ngrok2/ngrok.yml

          echo "Starting ngrok..."
          $(brew --prefix)/bin/ngrok tcp 5900 > ngrok.log 2>&1 &

          sleep 5
          echo "Ngrok logs:"
          tail -f ngrok.log

      - name: Launch Chrome in kiosk mode
        run: |
          open -a "Google Chrome" --args --kiosk https://www.google.com

      - name: Keep runner alive (no-op)
        run: tail -f /dev/null

