name: macOS Chrome VNC

on: [workflow_dispatch]

jobs:
  chrome-vnc:
    runs-on: macos-latest

    steps:
      - name: Setup Chrome + VNC
        run: |
          echo "🧠 Keep session alive"
          caffeinate -dims &

          echo "📺 Enable screen sharing (VNC)"
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -privs -all -restart -agent -console

          echo "🧼 Hide Dock and Menu bar"
          defaults write com.apple.dock autohide -bool true
          defaults write NSGlobalDomain _HIHideMenuBar -bool true
          killall Dock || true

      - name: Install ngrok
        run: |
          brew install --no-quarantine ngrok
          echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ~/.ngrok2/ngrok.yml

      - name: Start ngrok tunnel
        run: |
          nohup ngrok tcp 5900 > ngrok.log &
          sleep 5
          echo "🧪 Ngrok tunnel started"
          cat ngrok.log

      - name: Launch Chrome in kiosk mode
        run: |
          open -a "Google Chrome" --args --kiosk https://google.com
          echo "✅ Chrome launched"

      - name: Wait so Chrome stays open
        run: sleep 60000000
