name: macOS Chrome VNC

on: [workflow_dispatch]

jobs:
  chrome-vnc:
    runs-on: macos-latest

    steps:
      - name: Keep session awake
        run: caffeinate -dims &

      - name: Enable screen sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -privs -all -restart -agent -console

      - name: Hide Dock and menu bar
        run: |
          defaults write com.apple.dock autohide -bool true
          defaults write NSGlobalDomain _HIHideMenuBar -bool true
          killall Dock || true

      - name: Install Chrome (via Homebrew)
        run: |
          brew install --cask google-chrome

      - name: Install ngrok
        run: |
          brew install --no-quarantine ngrok
          mkdir -p ~/.ngrok2
          echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ~/.ngrok2/ngrok.yml

      - name: Start ngrok tunnel
        run: |
          nohup ngrok tcp 5900 > ngrok.log 2>&1 &
          sleep 6
          cat ngrok.log | grep -E "tcp://"

      - name: Launch Chrome in kiosk mode
        run: |
          open -a "Google Chrome" --args --kiosk https://www.google.com

      - name: Keep session alive for 10 minutes
        run: sleep 600000000
